TESTER=perl ../tester.pl

.PHONY: test
test:
	$(TESTER) test-no-input.txt
	$(TESTER) test-no-output.txt
	$(TESTER) test-no-underbar.txt
	$(TESTER) test-unknown-switch.txt
	$(TESTER) test-unknown-switch2.txt
